#SEARCH FOR THE ERRORS(404,200,504 ....)
#GET AN IDEA ABOUT APIs
#WHAT ARE THE TECHNOLOGIES TO BUILD WEB AND MOBILE APPLICATIONS
#WHY PEOPLE ARE USING MERN STACKS TODAY
print("\n","Flask".center(100,'-'),"\n")
